/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistascap;

/**
 *
 * @author Jonat
 */
public class v1 extends javax.swing.JFrame {

    /**
     * Creates new form v1
     */
    public v1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDeportista = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnEstudiante = new javax.swing.JButton();
        btnLicenciado = new javax.swing.JButton();
        btnPersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(55, 94, 151));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contactos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 20, 243, 60);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 90, 800, 20);

        btnDeportista.setBackground(new java.awt.Color(255, 255, 255));
        btnDeportista.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnDeportista.setForeground(new java.awt.Color(55, 94, 151));
        btnDeportista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/sport.png"))); // NOI18N
        btnDeportista.setText("Deportista");
        btnDeportista.setBorder(null);
        btnDeportista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeportista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeportista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeportistaActionPerformed(evt);
            }
        });

        btnDoctor.setBackground(new java.awt.Color(255, 255, 255));
        btnDoctor.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnDoctor.setForeground(new java.awt.Color(55, 94, 151));
        btnDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/doctor.png"))); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.setBorder(null);
        btnDoctor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoctor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        btnEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        btnEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnEstudiante.setForeground(new java.awt.Color(55, 94, 151));
        btnEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/student.png"))); // NOI18N
        btnEstudiante.setText("Estudiante");
        btnEstudiante.setBorder(null);
        btnEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });

        btnLicenciado.setBackground(new java.awt.Color(255, 255, 255));
        btnLicenciado.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnLicenciado.setForeground(new java.awt.Color(55, 94, 151));
        btnLicenciado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/employee.png"))); // NOI18N
        btnLicenciado.setText("Licenciado");
        btnLicenciado.setBorder(null);
        btnLicenciado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLicenciado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLicenciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciadoActionPerformed(evt);
            }
        });

        btnPersona.setBackground(new java.awt.Color(255, 255, 255));
        btnPersona.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnPersona.setForeground(new java.awt.Color(55, 94, 151));
        btnPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/user.png"))); // NOI18N
        btnPersona.setText("Persona");
        btnPersona.setActionCommand("Estudiante");
        btnPersona.setBorder(null);
        btnPersona.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersona.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(btnDeportista, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btnPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnLicenciado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeportista, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLicenciado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        // TODO add your handling code here:
        vAgregarEstudiante ven = new vAgregarEstudiante();
        ven.setVisible(true);
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaActionPerformed
        // TODO add your handling code here:
        vAgregarPersona ven = new vAgregarPersona();
        ven.setVisible(true);
    }//GEN-LAST:event_btnPersonaActionPerformed

    private void btnLicenciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciadoActionPerformed
        // TODO add your handling code here:
        vAgregarLicenciado ven = new vAgregarLicenciado();
        ven.setVisible(true);
    }//GEN-LAST:event_btnLicenciadoActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        vAgregarDoctor ven = new vAgregarDoctor();
        ven.setVisible(true);
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnDeportistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeportistaActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        vAgregarDeportista ven = new vAgregarDeportista();
        ven.setVisible(true);
    }//GEN-LAST:event_btnDeportistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeportista;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnLicenciado;
    private javax.swing.JButton btnPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
