/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistascap;

/**
 *
 * @author aadmon
 */
public class vContactosDoctor extends javax.swing.JFrame {

    /**
     * Creates new form vContactosDoctor
     */
    public vContactosDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscarDoc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIDDoc = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarDoc = new javax.swing.JButton();
        btnEliminarDoc = new javax.swing.JButton();
        btnModificarDoc = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb2Doc = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1Doc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarDoc.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarDoc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnBuscarDoc.setForeground(new java.awt.Color(55, 94, 151));
        btnBuscarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/find-my-friend.png"))); // NOI18N
        btnBuscarDoc.setBorder(null);
        btnBuscarDoc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBuscarDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDocActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 64, 51));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 94, 151));
        jLabel3.setText("ID: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        txtIDDoc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtIDDoc.setBorder(null);
        jPanel1.add(txtIDDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 72, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(55, 94, 151));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 72, 20));

        jPanel3.setBackground(new java.awt.Color(55, 94, 151));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contactos");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(280, 20, 200, 45);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(10, 70, 700, 20);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 80));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 94, 151));
        jLabel2.setText("Contactos Doctores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        btnAgregarDoc.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarDoc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAgregarDoc.setForeground(new java.awt.Color(55, 94, 151));
        btnAgregarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/add-contact.png"))); // NOI18N
        btnAgregarDoc.setText("Agregar");
        btnAgregarDoc.setBorder(null);
        btnAgregarDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDocActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 137, 56));

        btnEliminarDoc.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarDoc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnEliminarDoc.setForeground(new java.awt.Color(55, 94, 151));
        btnEliminarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/rubbish-bin.png"))); // NOI18N
        btnEliminarDoc.setText("Eliminar");
        btnEliminarDoc.setBorder(null);
        btnEliminarDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDocActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 137, 56));

        btnModificarDoc.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarDoc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnModificarDoc.setForeground(new java.awt.Color(55, 94, 151));
        btnModificarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/progress-arrows.png"))); // NOI18N
        btnModificarDoc.setText("Modificar");
        btnModificarDoc.setBorder(null);
        btnModificarDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDocActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 137, 56));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(55, 94, 151));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/back-arrow.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, 80, 60));

        tb2Doc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb2Doc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 350, 380));

        tb1Doc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb1Doc);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 300, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarDocActionPerformed

    private void btnAgregarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarDocActionPerformed

    private void btnEliminarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDocActionPerformed

    private void btnModificarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarDocActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vContactosDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vContactosDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vContactosDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vContactosDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vContactosDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarDoc;
    public javax.swing.JButton btnBuscarDoc;
    public javax.swing.JButton btnEliminarDoc;
    public javax.swing.JButton btnModificarDoc;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tb1Doc;
    public javax.swing.JTable tb2Doc;
    public javax.swing.JTextField txtIDDoc;
    // End of variables declaration//GEN-END:variables
}
