/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistascap;

/**
 *
 * @author aadmon
 */
public class vContactosDeportista extends javax.swing.JFrame {

    /**
     * Creates new form vContactosDeportista
     */
    public vContactosDeportista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregarDep = new javax.swing.JButton();
        btnEliminarDep = new javax.swing.JButton();
        btnModificarDep = new javax.swing.JButton();
        btnBuscarDep = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarDep.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarDep.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAgregarDep.setForeground(new java.awt.Color(55, 94, 151));
        btnAgregarDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/add-contact.png"))); // NOI18N
        btnAgregarDep.setText("Agregar");
        btnAgregarDep.setBorder(null);
        btnAgregarDep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDepActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 137, 56));

        btnEliminarDep.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarDep.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnEliminarDep.setForeground(new java.awt.Color(55, 94, 151));
        btnEliminarDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/rubbish-bin.png"))); // NOI18N
        btnEliminarDep.setText("Eliminar");
        btnEliminarDep.setBorder(null);
        btnEliminarDep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 137, 56));

        btnModificarDep.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarDep.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnModificarDep.setForeground(new java.awt.Color(55, 94, 151));
        btnModificarDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/progress-arrows.png"))); // NOI18N
        btnModificarDep.setText("Modificar");
        btnModificarDep.setBorder(null);
        btnModificarDep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDepActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 137, 56));

        btnBuscarDep.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarDep.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnBuscarDep.setForeground(new java.awt.Color(55, 94, 151));
        btnBuscarDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/find-my-friend.png"))); // NOI18N
        btnBuscarDep.setBorder(null);
        btnBuscarDep.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBuscarDep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDepActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 64, 51));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(55, 94, 151));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistascap/img/back-arrow.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, 80, 60));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 94, 151));
        jLabel3.setText("ID: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 72, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(55, 94, 151));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 72, 20));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 94, 151));
        jLabel2.setText("Contactos Deportistas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(55, 94, 151));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contactos");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(280, 20, 200, 45);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(10, 70, 700, 20);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarDepActionPerformed

    private void btnEliminarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDepActionPerformed

    private void btnModificarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarDepActionPerformed

    private void btnBuscarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarDepActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vContactosDeportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vContactosDeportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vContactosDeportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vContactosDeportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vContactosDeportista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDep;
    private javax.swing.JButton btnBuscarDep;
    private javax.swing.JButton btnEliminarDep;
    private javax.swing.JButton btnModificarDep;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
